[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

[env]
ESP_LOG = "info"
WIFI_SSID = "YourSSID"
WIFI_PASSWORD = "YourPassword"
YGG_PEER1 = "1.2.3.4:12345"
YGG_PEER2 = ""
YGG_PEER3 = ""
YGG_LISTEN_PORT = "2000"

[unstable]
build-std = ["alloc", "core"]
